package-lock.json
package.json
src/chain/event-watcher.js
src/chain/index.js
src/client/cli.js
src/client/client.js
src/client/index.js
src/client/wallet.js
src/config/default.js
src/server/routes.js

[WIP] Basic command line client for Plasma chain

---

contracts/ParsecBridge.sol

Needed for the node: https://github.com/parsec-labs/parsec-node/pull/6#discussion_r193317162

Make slots and epochLength public

---

contracts/ParsecBridge.sol

Needed for storing a tendermint public key of a validator

address → bytes32 for tendermint/newTendermint field in Slot

---

contracts/ParsecBridge.sol

Just an event for the token registration

NewToken event

---

contracts/mocks/SimpleToken.sol
test/parsecBridge.js

Bridge already migrated to good-old approve+call combo (https://github.com/parsec-labs/parsec-bridge-ui/pull/30)

remove ERC827 from tests

---

contracts/Migrations.sol
contracts/ParsecBridge.sol
contracts/PriorityQueue.sol
contracts/TxLib.sol
contracts/mocks/SimpleToken.sol
contracts/mocks/TxMock.sol
package.json

solc: mixed → 0.4.24
truffle: 4.0.5 → 4.1.13
OZ: 1.10.0 → 1.12.0

bump solc, truffle and open-zeppelin versions

---

contracts/ParsecBridge.sol
contracts/TxLib.sol
package.json
test/parsecBridge.js
test/txLib.js

more ERC721 goodness

---

contracts/ParsecBridge.sol
contracts/TxLib.sol
contracts/mocks/TxMock.sol
package.json
test/txLib.js

Related to https://github.com/parsec-labs/parsec-lib/pull/23

Use ethereum signing scheme

---

contracts/ParsecBridge.sol
test/parsecBridge.js

fix: only owner should be able to start exit

---

contracts/DepositHandler.sol
contracts/ExitHandler.sol
contracts/Vault.sol

 ______gap added in the end of inherited contracts

---

contracts/ExitHandler.sol
contracts/FastExitHandler.sol
test/exitHandler.js
test/fastExitHandler.js
test/helpers/index.js
test/helpers/submitNewPeriodWithTx.js

More Viable Plasma Episode 1 — Youngest Inputs

---

contracts/ExitHandler.sol
contracts/FastExitHandler.sol
package-lock.json
package.json
test/exitHandler.js
test/helpers/time.js
test/helpers/web3.js

Consolidate transaction inputs are unsigned, hence an operator could create and include invalid consolidate transactions to:
a) challenge valid exits.
b) decrease the priority of funds in exit queue by consolidating them,
putting the priority lower than his own transaction in the latest block.
The following invalid transactions are possible:
- consolidates with out-of-no-where inputs. (a,b)
- consolidates with inputs from UTXOs of other owners. (a,b)
- consolidates with inputs from spent UTXOs of same owner. (a)
- consolidates with duplicate inputs. (a)
A verification process is introduced with half the duration of the exit procedure. During this verification a transaction can be challenged before it is whitelisted to be used in an exit challenge. We use this verification process to …

enable consolidate transaction challenges

---

contracts/MinGov.sol
contracts/mocks/BridgeMock.sol
contracts/mocks/OperatorMock.sol
contracts/mocks/VaultMock.sol
package-lock.json
package.json
test/helpers/time.js
test/helpers/web3.js
test/minGov.js

simply copied over, no changes to logic.

move minGov from network repo to here

---

contracts/FastExitHandler.sol
test/fastExitHandler.js

Resolves https://github.com/leapdao/leap-contracts/issues/104

Fix fast exit handler

---

contracts/Bridge.sol
contracts/MinGov.sol
contracts/POSoperator.sol
contracts/PoaOperator.sol
contracts/SwapExchange.sol
contracts/SwapRegistry.sol
contracts/mocks/MintableToken.sol
contracts/test/BridgeUpgradeTest.sol
contracts/zos/UpgradeabilityProxy.sol
migrations/2_deploy.js
test/bridge.js
test/bridgeUpgrade.js
test/depositHandler.js
test/exitHandler.js
test/fastExitHandler.js
test/poaOperator.js
test/posOperator.js
test/swapRegistry.js
test/vault.js

Reward Payment Contract

---

test/minGov.js

Resolves https://github.com/leapdao/leap-contracts/issues/95
@troggy I think https://github.com/leapdao/leap-contracts/issues/95 is not an issue, because already implemented here: https://github.com/leapdao/leap-contracts/blob/master/contracts/Adminable.sol#L38-L55
added a test in this PR and it passed.

added dedicated read admin test

---

.solcover.js
.travis.yml
package.json
scripts/coverage.sh
truffle.js

travis coverage

---

contracts/ExitHandler.sol
test/exitHandler.js

Resolves https://github.com/leapdao/leap-contracts/issues/93

make exitDuration governable

---

contracts/mocks/BridgeMock.sol
test/minGov.js

debugging this: https://leapdao.slack.com/archives/CAAGW85BR/p1547761080026300

also test storage layout of implementation during upgrade

---

README.md
contracts/Bridge.sol
contracts/DepositHandler.sol
contracts/ExitHandler.sol
contracts/FastExitHandler.sol
contracts/MinGov.sol
contracts/PoaOperator.sol
contracts/SwapRegistry.sol
migrations/2_deploy_token.js
migrations/3_deploy_plasma.js
migrations/4_deploy_governance.js
test/minGov.js
test/nativeToken.js
test/posOperator.js
truffle-config.js

resolves https://github.com/leapdao/leap-contracts/issues/128
resolves https://github.com/leapdao/leap-contracts/issues/130

add swap registry to migration script

---

contracts/DepositHandler.sol
test/depositHandler.js
test/poaOperator.js

Resolves: https://github.com/leapdao/leap-contracts/issues/121

check deposit size and minGasPrice

---

contracts/SwapRegistry.sol
test/swapRegistry.js

resolves: https://github.com/leapdao/leap-contracts/issues/139

make slotToHeight public

---

contracts/FastExitHandler.sol
test/fastExitHandler.js

resolves https://github.com/leapdao/leap-node/issues/186

allow fast exit utxo to be destroyed on exit

---

contracts/ExitHandler.sol
contracts/TransferrableToken.sol
test/exitHandler.js

Resolves https://github.com/leapdao/leap-contracts/issues/123

Finalise multiple exits

---

contracts/TxLib.sol
contracts/mocks/TxMock.sol
package.json
scripts/test.sh
test/txLib.js
yarn.lock

resolves https://github.com/leapdao/leap-contracts/issues/145

added simple spend condition to TxLib

---

migrations/utils/writeConfig.js

related to https://github.com/leapdao/bridge-ui/issues/188

expose networkdId

---

migrations/1_initial_migration.js
migrations/3_deploy_plasma.js
migrations/4_deploy_governance.js
truffle-config.js

Solves #153 without using fragile hardcoded individual estimates

no individual estimates in migrations

---

contracts/TxLib.sol
package.json
test/txLib.js
yarn.lock

TxLib: Support for NSTs

---

migrations/4_deploy_governance.js

For local deployment.
Also: do not transfer ownership to governance if deploying on localnet

feat(deploy): optionally seed given localnet account with ETH, LEAP and some NFTs

---

contracts/SunDAI.sol
test/sunDai.js

This reapplies #165 again as it is missing in master (probably due to reverted merge in the former branch)

recover sunDAI contract PR merge (#165)

---

contracts/ExitHandler.sol
contracts/IExitHandler.sol
contracts/mocks/SpendingCondition.sol
test/exitHandler.js

resolves https://github.com/leapdao/leap-contracts/issues/147

allow spending conditions to exit

---

contracts/SparseMerkleTree.sol
test/helpers/SmtLib.js
test/sparseMerkleTree.js

foundation for https://github.com/leapdao/leap-contracts/issues/194

added simple sparse merkle tree implementation

---

contracts/SparseMerkleTree.sol
package.json
test/helpers/SmtLib.js
test/sparseMerkleTree.js

solves [#194](https://github.com/leapdao/leap-contracts/issues/194)

Extending key length in SMT to 160-bit

---

truffle-config.js

fix(build): increase gas limit for ExitHandler deployment to work

---

.env.template
README.md
truffle-config.js

fix(build): use Infura V3 provider URLs, configurable via ENV variables

---

truffle-config.js

fix: increase gas limit for mainnet so it is enough for FastExitHandler

---

contracts/MinGov.sol
contracts/Vault.sol
contracts/mocks/VaultMock.sol
migrations/3_deploy_plasma.js
test/depositHandler.js
test/exitHandler.js
test/fastExitHandler.js
test/minGov.js
test/posOperator.js
test/swapRegistry.js
test/vault.js

resolves https://github.com/leapdao/leap-contracts/issues/218

unite token registration functions

---

contracts/PoaOperator.sol
test/poaOperator.js
test/posOperator.js

... until it is fully implemented in the node.

make submit period backwards compatible

---

contracts/ERC1948.sol
contracts/ERC1949.sol
contracts/mocks/SpaceDustNFT.sol
test/erc1949.js
test/exitHandler.js

Create ERC1949 with `ERC1949.new("Super name", "TICKER")`

feat: make ERC1948 enumerable and ERC1949 named (with metadata)

---

contracts/ExitHandler.sol
test/exitHandler.js

resolves https://github.com/leapdao/leap-contracts/issues/219

have spending conditions pass through

---

contracts/Adminable.sol
test/bridge.js

So it is easier for users to find the actual code.

feat: expose proxies implementations

---

contracts/Bridge.sol
contracts/PoaOperator.sol
migrations/3_deploy_plasma.js
test/poaOperator.js
test/posOperator.js
yarn.lock

resolves https://github.com/leapdao/leap-contracts/issues/212
this will help in the review: https://docs.google.com/drawings/d/13oFjua-v_E_yaFYUbralluI-EysgtTaZb_sSgGbxG_A

cas challenge

---

contracts/ERC1948.sol
contracts/ERC1949.sol
contracts/PoaOperator.sol

small fixes

---

contracts/misc/BountyPayout.sol
contracts/misc/IColony.sol
contracts/mocks/Colony.sol
test/bountyPayout.js

resolves https://github.com/leapdao/meta/issues/141

bounty payout

---

contracts/misc/BountyPayout.sol
test/bountyPayout.js

resolves https://github.com/leapdao/leap-contracts/issues/248

bounty payout v2

---

contracts/PoaOperator.sol
contracts/mocks/PoaOperatorMock.sol
test/poaOperator.js

Minimum allow number is a largest slot id taken.
Resolves #120

fix: simple check for setting smaller epochLength values

---

contracts/ERC1948.sol
contracts/ERC1948Mint.sol
contracts/ERC1949.sol
contracts/ERC1949Breed.sol
contracts/ExitHandler.sol
contracts/MinGov.sol
contracts/PoaOperator.sol
contracts/SparseMerkleTree.sol
contracts/SwapRegistry.sol
contracts/TxLib.sol
contracts/Vault.sol
contracts/misc/BountyPayout.sol
contracts/misc/IColony.sol
contracts/mocks/Colony.sol
contracts/mocks/SpaceDustNFT.sol
contracts/mocks/SpendingCondition.sol
contracts/mocks/TxMock.sol
contracts/proxies/AdminableProxy.sol
contracts/proxies/BridgeProxy.sol
contracts/proxies/ExitHandlerProxy.sol
contracts/proxies/OperatorProxy.sol
contracts/zos/Initializable.sol

partially resolves https://github.com/leapdao/leap-contracts/issues/178

chore(lint): resolve trivial linting warnings

---

contracts/Adminable.sol
contracts/ERC1948Mint.sol
contracts/ERC20Mint.sol
contracts/ERC721Mint.sol
contracts/FastExitHandler.sol
contracts/MinGov.sol
contracts/PosOperator.sol
contracts/TxLib.sol
contracts/Vault.sol
contracts/mocks/SpaceDustNFT.sol
contracts/zos/AdminUpgradeabilityProxy.sol
contracts/zos/UpgradeabilityProxy.sol

resolves https://github.com/leapdao/leap-contracts/issues/238

add revert messages

---

migrations/5_update_contracts.js

Can be used for contract update test scenarious like https://github.com/leapdao/leap-sandbox/issues/32
Usage:
1. checkout updated contract version
2. `yarn compile`
3. CONFIG=<path to network config> ./node_modules/.bin/truffle deploy --f 5

feat: add migration to update contracts on the running network

---

contracts/PoaOperator.sol
migrations/5_update_contracts.js
test/poaOperator.js

this is usefull if a contract without bitmap is updated to a contract with bitmap.

allow to rebuild taken slots bitmap

---

contracts/HeartbeatToken.sol

TokenId = timestamp + slot owner + slot id

feat: add simple HeartbeatToken contract

---

contracts/misc/PaymentSplitter.sol
test/paymentSplitter.js

should split an ETH payment to array of recipients according to their shares.

contract to split ETH payments from contract wallet

---

.github/ISSUE_TEMPLATE/bounty.md

Copied from https://github.com/leapdao/meta/blob/master/.github/ISSUE_TEMPLATE/bounty.md

Create bounty issue template
